insert into profiles (name) values ('admin');
insert into profiles (name) values ('user');
insert into profiles (name) values ('helper');

INSERT INTO users(first_name,last_name,phone,email,password,field_name,original_name,encoding,mimetype,destination,filename,path,size, profile_id) VALUES ('Flavia','Frutos',1215121515,'flafrutos@gmail.com','$2a$10$UPZeZXZaGx7mG27F1poS/urV3YiD.74BcKixE1.b1pTwuUGz5PG2C','userImage','descargas.jpg','7bit','image/jpeg','./public/images/userImage','1653850478895_img.jpg','public\images\userImage\1653850478895_img.jpg',9986,1);
INSERT INTO users(first_name,last_name,phone,email,password,field_name,original_name,encoding,mimetype,destination,filename,path,size,profile_id) VALUES ('Carlos','Gonzalez',12345687987897987,'carlosgonchi@gmail.com','$2a$10$KnSafbmLECIHNooc0njHMuBgfJPblb12yPW9xVBHCiyACq7Sx3C2e','userImage','Mark_Cuban_&_Doug_Ducey_(47384954432)_(cropped).jpg','7bit','image/jpeg','./public/images/userImage','1655060816701_img.jpg','public\images\userImage\1655060816701_img.jpg',29640,2);
INSERT INTO users(first_name,last_name,phone,email,password,field_name,original_name,encoding,mimetype,destination,filename,path,size,profile_id) VALUES ('Marcelo','Salas',4445512525,'msalas@gmail.com','$2a$10$b5/AFgMxNfT3FTQfj0Xu8OiLvXu3OfapIbz2KMZmS7Ry1ayA0wzNi','userImage','foto-perfil2.jpg','7bit','image/jpeg','./public/images/userImage','1655061196455_img.jpg','public\images\userImage\1655061196455_img.jpg',76182,2);
INSERT INTO users(first_name,last_name,phone,email,password,field_name,original_name,encoding,mimetype,destination,filename,path,size,profile_id) VALUES ('Carolina','Hernandez',784525365,'chernandez@outlook.com','$2a$10$ufm/0HSAUY1zHQR97pmGXuD6DlCctQwsqFKNkrjs/BzmnyBEnTm2W','userImage','foto-perfil.PNG','7bit','image/png','./public/images/userImage','1655061301728_img.PNG','public\images\userImage\1655061301728_img.PNG','170848',3);
INSERT INTO users(first_name,last_name,phone,email,password,field_name,original_name,encoding,mimetype,destination,filename,path,size,profile_id) VALUES ('Hernan','Pichot',784585256,'hpichot@yahoo.com','$2a$10$TMfDT8m/Jw8dJ2IAWHCjnOu/wZKiSyzNB8DHEwMP9RZHjaCx1mrb6','userImage','foto-perfil3.jpg','7bit','image/jpeg','./public/images/userImage','1655061340480_img.jpg','public\images\userImage\1655061340480_img.jpg',1746544,3);
INSERT INTO users(first_name,last_name,phone,email,password,field_name,original_name,encoding,mimetype,destination,filename,path,size,profile_id) VALUES ('Raul','Hernandez',12781412,'brauliohernandez@gmail.com','$2a$10$8RH1/clb6rffBA3/n0ne1OFBCiB41Efqn4bqCtwdFOJh3jnKiQhL.','userImage','foto-perfil4.jpg','7bit','image/jpeg','./public/images/userImage','1655061372561_img.jpg','public\images\userImage\1655061372561_img.jpg',1725046,3);
INSERT INTO users(first_name,last_name,phone,email,password,field_name,original_name,encoding,mimetype,destination,filename,path,size,profile_id) VALUES ('Flor','Rodriguez',12345671,'florirodriguez@gmail.com','$2a$10$UPm4lIWDjWxeqJMarfBjj.EDdQs8h6O8f/SSfD6kEzDAQYuycAETG','userImage','stefan-stefancik-QXevDflbl8A-unsplash.jpg','7bit','image/jpeg','./public/images/userImage','1655062037859_img.jpg','public\images\userImage\1655062037859_img.jpg',7727893,2);
INSERT INTO users(first_name,last_name,phone,email,password,field_name,original_name,encoding,mimetype,destination,filename,path,size,profile_id) VALUES ('Sofia','Gomez',114567854,'sof@gmail.com','$2a$10$i2FYun4agmv/AuwcCXx2B.h.tq.tgCcXrbHv/095XcsE/itmf3.C.','userImage','jake-nackos-IF9TK5Uy-KI-unsplash.jpg','7bit','image/jpeg','./public/images/userImage','1655062074608_img.jpg','public\images\userImage\1655062074608_img.jpg',974837,3);
INSERT INTO users(first_name,last_name,phone,email,password,field_name,original_name,encoding,mimetype,destination,filename,path,size,profile_id) VALUES ('Charly','Simpson',12145454,'charly@simpson.com','$2a$10$mz3k5eyikFB2da6dtqX7NOKjbydnyNmfWSZuHpgS3dHJXuCkVxHI6','userImage','jurica-koletic-7YVZYZeITc8-unsplash.jpg','7bit','image/jpeg','./public/images/userImage','1655062106418_img.jpg','public\images\userImage\1655062106418_img.jpg',3588801,3);
INSERT INTO users(first_name,last_name,phone,email,password,field_name,original_name,encoding,mimetype,destination,filename,path,size,profile_id) VALUES ('Franco','Rubik',14563654,'cuborubik@gmail.com','$2a$10$tQr8qeif0cZZW6oeDjinZug0PznsYebWLz8C8zSa610I22EpbPU8S','userImage','craig-mckay-jmURdhtm7Ng-unsplash.jpg','7bit','image/jpeg','./public/images/userImage','1655062154540_img.jpg','public\images\userImage\1655062154540_img.jpg',2202376,3);
INSERT INTO users(first_name,last_name,phone,email,password,field_name,original_name,encoding,mimetype,destination,filename,path,size,profile_id) VALUES ('Julian','Wan',2146456789,'juliwan@gmail.com','$2a$10$7C8T9w24vCLVYVWOqW/8X.ZIbJVJj2GUs6WJS4D2CCYO29MYulHxi','userImage','julian-wan-WNoLnJo7tS8-unsplash.jpg','7bit','image/jpeg','./public/images/userImage','1655062179137_img.jpg','public\images\userImage\1655062179137_img.jpg',2107075,3);
INSERT INTO users(first_name,last_name,phone,email,password,field_name,original_name,encoding,mimetype,destination,filename,path,size,profile_id) VALUES ('Albert','Tesla',78945645,'ellocoalbert@tesla.com','$2a$10$kp3joaBaUf6tuyiJm7Yb6.e2o2T95v4Eko1OrEzXfcODeWoqZVCGu','userImage','albert-dera-ILip77SbmOE-unsplash.jpg','7bit','image/jpeg','./public/images/userImage','1655062218192_img.jpg','public\images\userImage\1655062218192_img.jpg',2413831,2);
INSERT INTO users(first_name,last_name,phone,email,password,field_name,original_name,encoding,mimetype,destination,filename,path,size,profile_id) VALUES ('Alec','Coleman',1169519090,'acoleman85@gmail.com','$2a$10$chBiAwsjLFYNgckE4WQALOjyRomHkfjzWKU3mvj17u6DNnYebBqQC','userImage','IMG_20200307_100650648_copy.jpg','7bit','image/jpeg','./public/images/userImage','1655074606341_img.jpg','public\images\userImage\1655074606341_img.jpg',973728,1);

insert into oficios(name, image, usa_seguro) values ('Jardinería', 'bordeadora.jpg', 0);
insert into oficios(name, image, usa_seguro) values ('Plomería', 'Plomería.jpg', 0);
insert into oficios(name, image, usa_seguro) values ('Limpieza de Hogar', 'Limpieza-del-hogar.png', 0);
insert into oficios(name, image, usa_seguro) values ('Pintor', 'Pintor.jpg', 0);
insert into oficios(name, image, usa_seguro) values ('Electricista', 'electricista.jpg', 1);

INSERT INTO helpers(calle,numero,codigo_postal,provincia,barrio,oficio_id,anos_de_experiencia,tarifa,mas_buscados,descripcion, usuario_id) VALUES ('Donado',1971,1430,'CABA','Villa Ortuzar',1,1,250,1,'Phasellus sit amet erat. Nulla tempus. Vivamus in felis eu sapien cursus vestibulum. Proin eu mi. Nulla ac enim. In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem. Duis aliquam convallis nunc. Proin at turpis a pede posuere nonummy.',4);
INSERT INTO helpers(calle,numero,codigo_postal,provincia,barrio,oficio_id,anos_de_experiencia,tarifa,mas_buscados,descripcion, usuario_id) VALUES ('Congreso',2552,1500,'CABA','Nu�ez',1,2,240,0,'Fusce posuere felis sed lacus. Morbi sem mauris, laoreet ut, rhoncus aliquet, pulvinar sed, nisl. Nunc rhoncus dui vel sem. Sed sagittis. Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci.', 5);
INSERT INTO helpers(calle,numero,codigo_postal,provincia,barrio,oficio_id,anos_de_experiencia,mas_buscados,tarifa,descripcion,usuario_id) VALUES ('Lima',241,1001,'CABA','Montserrat',1,3,0,220,'Nam nulla. Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede. Morbi porttitor lorem id ligula. Suspendisse ornare consequat lectus. In est risus, auctor sed, tristique in, tempus sit amet, sem. Fusce consequat. Nulla nisl. Nunc nisl. Duis bibendum, felis sed interdum venenatis, turpis enim blandit mi, in porttitor pede justo eu massa. Donec dapibus.',6);
INSERT INTO helpers(calle,numero,codigo_postal,provincia,barrio,oficio_id,anos_de_experiencia,tarifa,mas_buscados,descripcion,usuario_id) VALUES ('Comanche',1561,1420,'Buenos Aires','Vicente Lopez',2,4,300,1,'Nulla neque libero, convallis eget, eleifend luctus, ultricies eu, nibh.',8);
INSERT INTO helpers(calle,numero,codigo_postal,provincia,barrio,oficio_id,anos_de_experiencia,tarifa,mas_buscados,descripcion,usuario_id) VALUES ('De La Vega',1560,1820,'CABA','Belgrano',2,5,310,1,'Suspendisse potenti. Cras in purus eu magna vulputate luctus.',9);
INSERT INTO helpers(calle,numero,codigo_postal,provincia,barrio,oficio_id,anos_de_experiencia,mas_buscados,tarifa,descripcion,usuario_id) VALUES ('Guemez',1533,1561,'Santa Fe','Los Pinos',5,15,1,8.89,'Vivamus in felis eu sapien cursus vestibulum. Proin eu mi. Nulla ac enim. In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem. Duis aliquam convallis nunc. Proin at turpis a pede posuere nonummy. Integer non velit. Donec diam neque, vestibulum eget, vulputate ut, ultrices vel, augue. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec pharetra, magna vestibulum aliquet ultrices, erat tortor sollicitudin mi, sit amet lobortis sapien sapien non mi. Integer ac neque.',10);
INSERT INTO helpers(calle,numero,codigo_postal,provincia,barrio,oficio_id,anos_de_experiencia,tarifa,mas_buscados, descripcion,usuario_id) VALUES ('Parana',1220,92822,'Buenos Aires','San Fernando',4,14,3.14,0,'Morbi ut odio. Cras mi pede, malesuada in, imperdiet et, commodo vulputate, justo.',11);
INSERT INTO users (first_name,last_name,phone,email,password,profile_id,field_name,original_name,encoding,mimetype,destination,filename,`path`,`size`) VALUES
	 ('jose ignacio paolini','Paolini',221555555,'joseignaciopaolini@gmail.com','$2a$10$zcdv90OFV3oR/XuL0y.ALOHuzdCaPPI.UbFICmFLhmu.RAK7BvqzK',1,'userImage','José Ignacio Paolini.jpg','7bit','image/jpeg','./public/images/userImage','1655864042460_img.jpg','public\\images\\userImage\\1655864042460_img.jpg',107576);




